### PR TITLE
Some UI improvements

### PR DESCRIPTION
**Pull request by AndreyEzhov**
Some UI improvements for RequestCell. The number of lines for URL label now is 0. It helps to display a long URL.

### CODE REVIEW

**Comment by colinhumber** [comment]
+1 to this

**Comment by pmusolino** [comment]
Super PR! Thanks @AndreyEzhov.

**Comment by pmusolino** [comment]
@AndreyEzhov some users have told me that some labels in the cells are not visible on iOS 10 (iPhone SE). I checked and it's actually like that. Can you understand what the reason is?

**Comment by AndreyEzhov** [comment]
@pmusolino Sorry, cannot define the problem :( could you please provide a screenshot?

Screenshot 2019-10-14 at 10 58 17 AM

**Pull request merged**
