### PR TITLE
Migrate to SPM

### LINKED ISSUE #112: Swift Package Manager SPM support?
When trying to use SPM I end up with this:

```
xcodebuild: error: Could not resolve package dependencies:
  Source files for target Wormholy should be located under 'Sources/Wormholy', or a custom sources path can be set with the 'path' property in Package.swift
 ```
 
 Do you by any chance plan to support SPM?

### PR DESCRIPTION
**Pull request by ipavlidakis**
- Migrated to SPM
- Introduced WormholySwift as a wrapper target for Swift files as SPM doesn't support multi-lang modules
- Cleaned up and update demo
- Removed configs as unnecessary
- Updated podfile

Resolves #112, #139

### CODE REVIEW

**Comment by ipavlidakis** [comment]
@pmusolino what do you think?

**Comment by gmoraleda** [comment]
It would be great to see this merged @pmusolino  🙌 
Thanks for the PR @ipavlidakis !

**Comment by dnKaratzas** [comment]
Could you please merge that?

**Comment by zdurlan** [comment]
Please merge this when possible, this will be of real help

**Comment by dnKaratzas** [comment]
@pmusolino the only diff I see is that the files moved to a different directory

**Comment by pmusolino** [comment]
@dnKaratzas [ActionableTableViewCell.xib](https://github.com/pmusolino/Wormholy/pull/116#diff-c2cd871fc855a1d7766598f8c6a465aa0b6849efd46dbefa3b12d0cd85f8ae6a) was not moved but has some changes for example.

**Comment by ipavlidakis** [comment]
@pmusolino I don't recall making changes to `.xib` files other than moving them to match the SPM file structure. The changes were probably made from the different version of Xcode, that's why you can see mainly changes on version fields

**Comment by dnKaratzas** [comment]
@pmusolino minor changes cause opened the `xib` on a different Xcode version.
Then onlly actual change I can spot is the module name
```customModule="WormholySwift"```

**Comment by mparmar-covantex** [comment]
Right. I agree with @dnKaratzas & @ipavlidakis as well

Can you please merge it? @pmusolino 

Thank you in advance..

**Comment by mehulparmar4ever** [comment]
Hello @pmusolino, Can you please merge this PR? cc: @ipavlidakis 

Thanks.

**Comment by azdurlan-spectra** [comment]
We really need this.

**Comment by mehulparmar4ever** [comment]
@ipavlidakis @pmusolino  Any **updates**?

**Comment by pmusolino** [comment]
@ipavlidakis could I ask you to fix the merge conflicts, so I can review this PR and merge it?

**Comment by pmusolino** [comment]
@ipavlidakis do you have time to fix the merge conflicts? It would be really helpful to offer SPM 🙌 thanks!

**Comment by ipavlidakis** [comment]
Sure, i'm on it and should have something ready in following few hours 🤞🏻

**Comment by pmusolino** [comment]
@ipavlidakis do you have any update on this? 🙏

**Comment by ipavlidakis** [comment]
Hey @pmusolino sorry for the delay. I have updated the PR and I'm going to test it tomorrow. It will be great if you can also check it and let me know your thoughts. Thanks

**Comment by pmusolino** [comment]
Thanks @ipavlidakis! Can I test it right away or should you need to apply extra changes?

**Comment by ipavlidakis** [comment]
Feel free to test it as it is.

**Comment by pmusolino** [comment]
I'll test it this weekend and early this week, thanks @ipavlidakis 🙏

**Comment by parmar-mehul** [comment]
Hello @ipavlidakis ,

Below line should be removed, There is no similar file.
`"Support Files/Assets.xcassets"`

Screenshot 2024-03-26 at 9 43 51 AM

And, 
You can delete this two files as well, May be, That is old structure. Remove it and Build demo app, It works.

Screenshot 2024-03-26 at 9 40 17 AM

Screenshot 2024-03-26 at 9 40 33 AM

**Comment by pmusolino** [comment]
Thanks, @parmar-mehul for the collaboration 🚀 let's wait for @ipavlidakis to review and merge your PR.

**Comment by parmar-mehul** [comment]
> Thanks, @parmar-mehul for the collaboration 🚀 let's wait for @ipavlidakis to review and merge your PR.

Hello @ipavlidakis, Do we have any updates? It has been a week now! Hope we will get this done soon. Thank you for your time!!

**Comment by pmusolino** [comment]
@ipavlidakis let us know when you will be able to take care of this, thanks! 🙌

**Comment by ipavlidakis** [comment]
Sorry for the wait folks but that ended up being much more complicated than it was when the PR was initially opened (that combined with limited personal time to work on it made me pick up on it late). 

I tested the current changes with a project integrating the library via SPM and made sure that embedded Demo project builds. It would be great if any of you is available to do a quick check with Cocoapods & Carthage as I haven't used them in a very long time and it may take me some time to set them up.

@pmusolino let me know your thoughts.

**Comment by pmusolino** [comment]
Thank you @ipavlidakis for finding the time!

I did a test with Cocoapods, and I got an error in this file:

Screenshot 2024-04-18 at 17 15 52

While, commenting it, allowed me to compile the app and launch WormHoly, and everything seems to work properly.

**Comment by ipavlidakis** [comment]
Thanks for checking @pmusolino. I just updated podspec to ignore the file. do you mind trying one more time?

**Comment by pmusolino** [comment]
The issue still persists @ipavlidakis, it seems the file has not been excluded, I'm still able to see it.

**Comment by ipavlidakis** [comment]
Interesting, maybe the pattern was wrong. I simplified it to be just the folder. Hope it works now

**Comment by pmusolino** [comment]
@ipavlidakis Now it works like a charm. I also tried to run the demo, and it works well! I'll review the code ASAP, and we can merge it. 👏

**Comment by pmusolino** [comment]
@ipavlidakis I started testing it with SPM. It has been integrated correctly into a project, with no issues. But Wormholy cannot be presented: manual fire or shake doesn't work. Any idea?

**Comment by federicosacca** [comment]
Hi @pmusolino, the problem is that the class at line 7 in the file (1) is 0x0 (null), because the correct class seems to be _WormholySwift. Maybe there is an issue in the package.swift declaration. Even if you change the class from @Wormholy.Wormholy to @Wormholy._WormholySwift, you will have problem in Flow.storyboard instantation, file (2).

(1) https://github.com/pmusolino/Wormholy/blob/master/Sources/Objc/WormholyConstructor.m
(2) https://github.com/pmusolino/Wormholy/blob/master/Sources/UI/Flow.storyboard

**Comment by ipavlidakis** [comment]
@pmusolino do you have some code i can look into?

**Comment by pmusolino** [comment]
@ipavlidakis no code I can share. In any case, it's a project with both CocoaPods and SPM. Do you have the time to check what @federicosacca mentioned above?

**Comment by pmusolino** [comment]
@ipavlidakis do you have any news on this?

**Comment by parmar-mehul** [comment]
Hello Team, Can you please release latest build?

**Comment by acamcor-seatcode** [comment]
Hi! We are waiting too. It would be cool to have it. Tx!

**Comment by parmar-mehul** [comment]
Hello @pmusolino, Can you merge changes? Thanks!

**Comment by pmusolino** [comment]
@ipavlidakis 🙌 do you have time to double-check the issues mentioned before?

**Comment by Abhishek2383** [comment]
@pmusolino : did we, by any chance got the time to merge this branch for SPM support for Wormholy

**Comment by Silviuvr** [comment]
Still not merged? Can you please merge it if everything works fine? @pmusolino

**Comment by pmusolino** [comment]
Hi there, @Abhishek2383 and @Silviuvr. Unfortunately, this still doesn't work as expected. Additionally, I believe it is not possible to target only debugging or only production in Swift Package Manager, so it will be your responsibility to manage this condition on your apps.

**Comment by julian-zatloukal** [comment]
Had to remove this dependency in favor of SPM, sad because this extension is great

**Comment by pmusolino** [comment]
Guys, Wormholy 2 is coming soon, hopefully by the end of the day. It's a big rewrite of the library, with also SPM support!

**Comment by pmusolino** [comment]
Guys, the new release 2.0.0 that support SPM is online! [Check it out now](https://github.com/pmusolino/Wormholy/releases/tag/2.0.0).

Closing this PR, but feel free to open new issues here in Github if you find any problem with the update. Thanks!

**Pull request closed without merging**
