### PR TITLE
Updated project to current Swift 4 standards.

### PR DESCRIPTION
**Pull request by michaelharrigan**
I was trying to build with Wormholy, in iOS 12 with Xcode 10, as a pod, when I was getting a lot of errors having to do with changes to Swift. 

So I forked it really quick and ran the automatic converter with Swift.

I was having issue trying to export this as a framework and manually adding it to my project to test the changes.

### CODE REVIEW

**Comment by michaelharrigan** [comment]
**Update:** I pointed my pod file at my forked repo, installed, and built with Swift 4. Everything is working as it should now.

**Comment by pmusolino** [comment]
Thanks @michaelharrigan !

I will analyze your pull request as soon as possible.

-Paolo

**Comment by StateMachineJunkie** [comment]
@pmusolino I really need for you to get on integrating this pull request. Apple is about to release iOS 12 and Xcode 10. When that happens, they are likely to stop accepting submissions from Xcode 9. I've converted the rest of my project over to the latest version of Swift and all I need is for your pod to be updated. Please help me out and analyze this pull request ASAP. Thanks.

**Comment by pmusolino** [comment]
I accepted this PR, that is pretty similar. https://github.com/pmusolino/Wormholy/pull/42

**Pull request closed without merging**
